# Note: awslogs-group value depends on `key_name` under terraform.tfvars

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:10.4.1
    restart: always
    container_name: cardano-node
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "${REGION}"                             # defined in sample-node-config/aws/terraform.tfvars
        awslogs-group: "${KEY_NAME}-${NETWORK}_instance_logs"   # defined in cloudwatch.tf
        awslogs-stream: "cardano_node-${NETWORK}"               # defined in cloudwatch.tf
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        mode: non-blocking
    volumes:
      - ../network:/network
    working_dir: /data
    environment:
      - CARDANO_SOCKET_PATH=/network/node.socket      # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/network/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/network/cardano-node/config.json"
      , "--topology", "/network/cardano-node/topology.json"
      , "--database-path", "/network/db"
      ]

  hydra-node:
    image: ghcr.io/cardano-scaling/hydra-node:1.1.0
    restart: always
    container_name: hydra-node
    logging:
      driver: "journald"
      # driver: "awslogs"
      # options:
      #   awslogs-region: "eu-west-3"                            # defined in variables.tf
      #   awslogs-group: "${KEY_NAME}-${NETWORK}_instance_logs"  # defined in cloudwatch.tf
      #   awslogs-stream: "hydra_node-${NETWORK}"                # defined in cloudwatch.tf
      #   tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
      #   mode: non-blocking
    volumes:
      - ~/config/${NETWORK}:/config:ro
      - ~/credentials:/credentials:ro
      - ~/credentials/members:/members:ro
      - ~/network:/network
      - ~/persistence:/data
    ports:
      - "5001:5001"
      - "4001:4001"
    command:
      [ "--node-id", "${KEY_NAME}"
      , "--api-host", "0.0.0.0"
      , "--listen", "0.0.0.0:5001"
      , "--advertise", "63.177.91.204:5001"
      , "--monitoring-port", "6000"
      , "--hydra-scripts-tx-id", "${HYDRA_SCRIPTS_TX_ID}"
      , "--hydra-signing-key", "/credentials/hydra-key.sk"
      , "--cardano-signing-key", "/credentials/cardano-key.sk"
      , "--ledger-protocol-parameters", "/config/protocol-parameters.json"
      # , "--mainnet"
      , "--testnet-magic", "${NETWORK_MAGIC}"
      , "--node-socket", "/network/node.socket"
      , "--persistence-dir", "/data"
      # hardcoded peers
      # Sasha
      , "--peer", "13.37.150.125:5001"
      , "--hydra-verification-key", "/members/sasha.hydra.vk"
      , "--cardano-verification-key", "/members/sasha.cardano.vk"
      # Dan
      , "--peer", "hydra.horizon-haskell.net:5005"
      , "--hydra-verification-key", "/members/dan.hydra.vk"
      , "--cardano-verification-key", "/members/dan.cardano.vk"
      # Franco
      , "--peer", "13.39.44.251:5001"
      , "--hydra-verification-key", "/members/franco.hydra.vk"
      , "--cardano-verification-key", "/members/franco.cardano.vk"
      # Noon
      , "--peer", "35.214.9.104:5005"
      , "--hydra-verification-key", "/members/noon.hydra.vk"
      , "--cardano-verification-key", "/members/noon.cardano.vk"
      # Sharan
      , "--peer", "35.181.137.127:5001"
      , "--hydra-verification-key", "/members/sharan.hydra.vk"
      , "--cardano-verification-key", "/members/sharan.cardano.vk"
      ]

  hydra-tui:
    image: ghcr.io/cardano-scaling/hydra-tui:unstable
    container_name: hydra-tui
    profiles:
      - tui
    command:
      [
      "--connect", "hydra-node:4001"
      , "--node-socket", "/network/node.socket"
      , "--testnet-magic", "${NETWORK_MAGIC}"
      , "--cardano-signing-key", "/credentials/cardano-key.sk"
      ]
    volumes:
      - ~/credentials:/credentials:ro
      - ~/network:/network

  hydraw:
    image: ghcr.io/cardano-scaling/hydraw:latest
    container_name: hydraw
    profiles:
      - hydraw
    environment:
      - HYDRAW_CARDANO_SIGNING_KEY=/data/cardano-key.sk
      - HYDRA_API_HOST=hydra-node:4001
    volumes:
      - .:/data:ro
    ports:
      - "80:1337"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  promtail:
    image: grafana/promtail:1.4.1
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
