name = "hydra/hydra-plutus"
version = "0.14.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'hydra/hydra-plutus'"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
