name: Check hlint

on:
  pull_request:

jobs:
  hlint:
    name: Check hlint
    runs-on: self-hosted
    steps:
    - name: ğŸ“¥ Checkout repository
      uses: actions/checkout@v4

    - name: ğŸ“ Check hlint
      run: |
        nix develop .#fmt --command hlint .
